---
# We use "override" instead of "ignore" to still see these issues.
# With the "failure-threshold" set to "warning" below, these should not make
# the test fail.
override: 
  info:
    # warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
    - DL3018
failure-threshold: warning